# Generated by Django 4.2 on 2024-08-06 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='name_artist',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='tittle',
            new_name='title',
        ),
    ]
